In [ ]:
import numpy as np
import matplotlib.pyplot as plt

runs = 600

Nmin= 1
Nmax = 10000
N = np.arange(Nmin,Nmax+1,1)
N_exp = np.tile(N, (runs,1))
print(N_exp)

all_M_values = np.zeros((runs, len(N)))


counter = 0

for n in N:
    M = np.zeros(runs)

    j = 0

    for _ in range(runs):
       
        sample = np.random.choice([-1,1], size = n, p = [0.5, 0.5]) 
  
        M[j] = np.sum(sample) 
        j +=  1

    all_M_values[:, counter] = M
    counter += 1



filename = f"./data_example_1_600_runs_10000_particles"

print(all_M_values)

np.savez(filename, N=N_exp, all_M_values = all_M_values) 




[[    1     2     3 ...  9998  9999 10000]
 [    1     2     3 ...  9998  9999 10000]
 [    1     2     3 ...  9998  9999 10000]
 ...
 [    1     2     3 ...  9998  9999 10000]
 [    1     2     3 ...  9998  9999 10000]
 [    1     2     3 ...  9998  9999 10000]]
[[   1.    0.   -3. ...  242. -191.   26.]
 [   1.    0.   -1. ... -140.   -9.  -34.]
 [   1.    0.   -1. ...    0.  -25.    0.]
 ...
 [  -1.    0.   -1. ...  -16. -127.  -18.]
 [   1.   -2.    1. ... -172. -167.   14.]
 [  -1.    2.    3. ...  182. -125.    0.]]
